# Copyright 2025 Xin Huang and Simon Chen
#
# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, please see
#
#    https://www.gnu.org/licenses/gpl-3.0.en.html


include: "rules/common.smk"
include: "rules/1_download.smk"
include: "rules/2_preprocess.smk"


if datasets_with_anc:

    include: "rules/3_polarization.smk"
    include: "rules/4.1_positive_selection_selscan.smk"
    include: "rules/4.2_positive_selection_selscan_xp.smk"


include: "rules/4.3_positive_selection_scikit-allel.smk"
include: "rules/4.4_positive_selection_scikit-allel_xp.smk"
include: "rules/5.1_balancing_selection_betascan.smk"
include: "rules/5.2_balancing_selection_scikit-allel.smk"
include: "rules/6_deleterious_dfe_dadi.smk"
include: "rules/7_plot_results.smk"


#report: "report/workflow.rst"


rule all:
    input:
        # selscan
        expand_1pop(
            "results/positive_selection/selscan/{species}/{dataset}/1pop/{ppl}/{method}_{maf}/{ppl}.normalized.{method}.maf_{maf}.top_{cutoff}.{type}.png",
            anc_only=True, **SELSCAN_KW, type=["scores", "gowinda.enrichment"],
        ),
        expand_1pop(
            "results/positive_selection/selscan/{species}/{dataset}/1pop/{ppl}/{method}_{maf}/{ppl}.normalized.{method}.maf_{maf}.top_{cutoff}.{type}.html",
            anc_only=True, **SELSCAN_KW, type=["outlier.genes", "gowinda.enrichment"],
        ),
        # selscan xp
        expand_2pop(
            "results/positive_selection/selscan/{species}/{dataset}/2pop/{pair}/{method}_{maf}/{pair}.normalized.{method}.maf_{maf}.top_{cutoff}.{type}.png",
            anc_only=True, **SELSCAN_XP_KW, type=["scores", "gowinda.enrichment"],
        ),
        expand_2pop(
            "results/positive_selection/selscan/{species}/{dataset}/2pop/{pair}/{method}_{maf}/{pair}.normalized.{method}.maf_{maf}.top_{cutoff}.{type}.html",
            anc_only=True, **SELSCAN_XP_KW, type=["outlier.genes", "gowinda.enrichment"],
        ),
        # betascan
        expand_1pop(
            "results/balancing_selection/betascan/{species}/{dataset}/{ppl}/m_{core_frq}/{ppl}.{ref_genome}.m_{core_frq}.b1.top_{cutoff}.{type}.png",
            **BETASCAN_KW, type=["scores", "gowinda.enrichment"],
        ),
        expand_1pop(
            "results/balancing_selection/betascan/{species}/{dataset}/{ppl}/m_{core_frq}/{ppl}.{ref_genome}.m_{core_frq}.b1.top_{cutoff}.{type}.html",
            **BETASCAN_KW, type=["outlier.genes", "gowinda.enrichment"],
        ),
        # dadi dfe
        expand_1pop(
            "results/dadi/{species}/{dataset}/dfe/{ppl}/html/{ppl}.{ref_genome}.{demog}.dm.fitted.html",
             **DADI_1D_KW,
        ),
        expand_1pop(
            "results/dadi/{species}/{dataset}/dfe/{ppl}/html/{ppl}.{ref_genome}.{demog}.{dfe}.dfe.fitted.html",
            **DADI_1D_KW, dfe=dadi_config["dfe_1d"],
        ),
        expand_1pop(
            "results/dadi/{species}/{dataset}/dfe/{ppl}/plots/{ppl}.{ref_genome}.{demog}.{dfe}.fitted.mut.prop.png",
            **DADI_1D_KW, dfe=dadi_config["dfe_1d"],
        ),
        expand_1pop(
            "results/dadi/{species}/{dataset}/dfe/{ppl}/html/{ppl}.{ref_genome}.{demog}.InferDM.top10.bestfits.html",
            **DADI_1D_KW,
        ),
        expand_1pop(
            "results/dadi/{species}/{dataset}/dfe/{ppl}/html/{ppl}.{ref_genome}.{demog}.{dfe}.{type}.html",
            **DADI_1D_KW, dfe=dadi_config["dfe_1d"],
            type=["godambe.ci", "InferDFE.top10.bestfits"],
        ),
        # moving tajima d
        expand_1pop(
            "results/positive_selection/scikit-allel/{species}/{dataset}/1pop/{ppl}/{method}/{window}_{step}/{ppl}.{method}.top_{cutoff}.{type}.png",
            **TAJIMAD_MOVING_KW, type=["scores", "gowinda.enrichment"],
        ),
        expand_1pop(
            "results/positive_selection/scikit-allel/{species}/{dataset}/1pop/{ppl}/{method}/{window}_{step}/{ppl}.{method}.top_{cutoff}.{type}.html",
            **TAJIMAD_MOVING_KW, type=["outlier.genes", "gowinda.enrichment"],
        ),
        expand_1pop(
            "results/balancing_selection/scikit-allel/{species}/{dataset}/{method}/{ppl}/{window}_{step}/{ppl}.{method}.top_{cutoff}.{type}.png",
            **TAJIMAD_MOVING_KW, type=["scores", "gowinda.enrichment"],
        ),
        expand_1pop(
            "results/balancing_selection/scikit-allel/{species}/{dataset}/{method}/{ppl}/{window}_{step}/{ppl}.{method}.top_{cutoff}.{type}.html",
            **TAJIMAD_MOVING_KW, type=["outlier.genes", "gowinda.enrichment"],
        ),
        # windowed tajima d
        expand_1pop(
            "results/positive_selection/scikit-allel/{species}/{dataset}/1pop/{ppl}/{method}/{window}_{step}/{ppl}.{method}.top_{cutoff}.{type}.png",
            **TAJIMAD_WINDOWED_KW, type=["scores", "gowinda.enrichment"],
        ),
        expand_1pop(
            "results/positive_selection/scikit-allel/{species}/{dataset}/1pop/{ppl}/{method}/{window}_{step}/{ppl}.{method}.top_{cutoff}.{type}.html",
            **TAJIMAD_WINDOWED_KW, type=["outlier.genes", "gowinda.enrichment"],
        ),
        expand_1pop(
            "results/balancing_selection/scikit-allel/{species}/{dataset}/{method}/{ppl}/{window}_{step}/{ppl}.{method}.top_{cutoff}.{type}.png",
            **TAJIMAD_WINDOWED_KW, type=["scores", "gowinda.enrichment"],
        ),
        expand_1pop(
            "results/balancing_selection/scikit-allel/{species}/{dataset}/{method}/{ppl}/{window}_{step}/{ppl}.{method}.top_{cutoff}.{type}.html",
            **TAJIMAD_WINDOWED_KW, type=["outlier.genes", "gowinda.enrichment"],
        ),
        # delta tajima d
        expand_2pop(
            "results/positive_selection/scikit-allel/{species}/{dataset}/2pop/{pair}/{method}/{window}_{step}/{pair}.{method}.top_{cutoff}.{type}.png",
            **DELTA_TAJIMAD_KW, type=["scores", "gowinda.enrichment"],
        ),
        expand_2pop(
            "results/positive_selection/scikit-allel/{species}/{dataset}/2pop/{pair}/{method}/{window}_{step}/{pair}.{method}.top_{cutoff}.{type}.html",
            **DELTA_TAJIMAD_KW, type=["outlier.genes", "gowinda.enrichment"],
        ),
        # dfe confidence intervals
        "results/plots/dfe/combined.dfe_params.svg",
