datasets:
  - config/1kg_high_cov.yaml
  - config/1kg_low_cov.yaml
  - config/greatape.yaml

selscan_config: "config/selscan.yaml"
betascan_config: "config/betascan.yaml"
dadi_config: "config/dadi-cli.yaml"
scikit_allel_config: "config/scikit-allel.yaml"

population_groups:
  AFR:
    color: "black"
    populations: [YRI]
  EAS:
    color: "gold"
    populations: [CHS]
  Pan:
    color: "#FF7F00"
    populations: [PPA]


