# Main configuration: links to individual dataset configs
datasets:
  - config/1000g_high.yaml
#  - config/1000g_low.yaml
  - config/greatape.yaml


# Shared tool configurations (applied to all datasets)
selscan_config: "config/selscan.yaml"
betascan_config: "config/betascan.yaml"
dadi_config: "config/dadi-cli.yaml"
scikit_allel_config: "config/scikit-allel.yaml"
