datasets:
  - config/1000g_high.yaml

selscan_config: "config/selscan.yaml"
betascan_config: "config/betascan.yaml"
dadi_config: "config/dadi-cli.yaml"
scikit_allel_config: "config/scikit-allel.yaml"

population_groups:
  AFR:
    color: "black"
    populations: [YRI]
  EAS:
    color: "gold"
    populations: [CHS]
